version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: rush01-tester
    main: .
    binary: rush01-tester
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: rush01-tester
    formats: [binary]
    name_template: "rush01-tester_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: nweber23
    name: skyscraper_puzzle_tester
